CREATE TABLE RAW_EM_DATA(
	SAMPLE_TIMESTAMP TIMESTAMP NOT NULL,
	GRID_POWER DOUBLE NOT NULL,
	PV_POWER DOUBLE NOT NULL,
	GRID_VOLTAGE DOUBLE NOT NULL,
	PV_VOLTAGE DOUBLE NOT NULL,
	PRIMARY KEY (SAMPLE_TIMESTAMP)
);

CREATE TABLE HOURLY_EM_ENERGY(
	FROM_TIMESTAMP TIMESTAMP NOT NULL,
	TO_TIMESTAMP TIMESTAMP NOT NULL,
	GRID_ENERGY_IN DOUBLE NOT NULL,
	GRID_ENERGY_OUT DOUBLE NOT NULL,
	PV_ENERGY_IN DOUBLE NOT NULL,
	PV_ENERGY_OUT DOUBLE NOT NULL,
	MAX_GRID_VOLTAGE DOUBLE NOT NULL,
	MIN_GRID_VOLTAGE DOUBLE NOT NULL,
	MAX_PV_VOLTAGE DOUBLE NOT NULL,
	MIN_PV_VOLTAGE DOUBLE NOT NULL,
	PRIMARY KEY (FROM_TIMESTAMP)
);
