DROP TABLE RAW_EM_DATA;

CREATE TABLE RAW_EM_DATA(
    DEVICE_LOCAL_IP_ADDRESS VARCHAR(255) NOT NULL,
    DEVICE_CHANNEL INTEGER NOT NULL,
    SAMPLE_TIMESTAMP TIMESTAMP NOT NULL,
    DEVICE_ID VARCHAR(255) NOT NULL,
    POWER DOUBLE NOT NULL,
    PRIMARY KEY (DEVICE_LOCAL_IP_ADDRESS, DEVICE_CHANNEL, SAMPLE_TIMESTAMP)
);